name = "worker-auth-providers"
type = "webpack"
account_id = "ea5d8d3c03a46b28e8c9f25ae1c09ca8"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

kv-namespaces = [
  { binding = "WORKER_AUTH_PROVIDERS_STORE", preview_id = "99e3d686a2b249a1b12a5ee49ba388d8", id = "99e3d686a2b249a1b12a5ee49ba388d8" }
]

[site]
bucket = "../dist/client"
entry-point = "."
